### ISSUE TITLE
Add FRBStats integration

### ISSUE THREAD

**Issue by Kaffeedor** [Kaffeedor/astro-dbot-public#3]
# About
Allow the bot to return information on [FRBs](https://en.wikipedia.org/wiki/Fast_radio_burst) by searching by name or a parameter

# Todo:
- [x] Discord integration @Kaffeedor 
- [ ] Search by other parameters (possibly through future API updates)
- [ ] Make more readable and format output messages (perhaps custom image) @technobird22 (@Kaffeedor for concept maybe)

# Sample
**Input:** $frb FRB20190806

**Output:** [{'dm': '1384.58', 'mjd': '58701.27581', 'utc': '2019-08-06 6:37:10', 'flux': '-', 'l': '91.5', 'frequency': '600', 'dec': '+59:24:00', 'ra': '19:39:43', 'frb': 'FRB 20190806A', 'ref': 'https://www.wis-tns.org/object/20190806a', 'snr': '9.11', 'telescope': 'CHIME', 'b': '17.32', 'fluence': '-', 'width': '-'}]

**Comment by Kaffeedor** [comment]
Added the basic Discord Bot (in a own file rn), doesnt have any Formating and only the functions the API has avivable atm.
Will add this to the main bot in the future and also add basic formating. When API gets updated I will add these functions. Meanwhile ill try to add them over other ways
